name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "21"

      - name: Install dependencies
        run: npm install

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: -----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEA4oL4aTFXjz9/Z3NdlmBRBlGiaeICpxkE59hWkKbCSkknASYA
IzXpA+gmCpjUd5tRe00DcXOqfYyrnQN9wAIFsV10OIZE9iEK8F3WKJ+X41g/lc+5
Cq2ilW7wF5BkOSgPtrHHV3ygK/Kwibn3QF87PKsYdQoSrA2HJEFu5Q/yUXKsOylx
xTNbXhhrS+5X3h5dnqae7Iy9vOi3xjAZclB4XHxMsMHYJ0/blSuITfKJXF620n08
kBxVXXab7pZLTYTpzfChaHz7TIVfPDv8GE8jIfKgPlxiv63xKb3qqk/Rv3Db8Vic
oVUbFjCAadYLJkEFeNau2k3SKqTufamLzdzRkwIDAQABAoIBAQCYTl6ARQhOLvEY
+46rRZpVuGCP98O23fDZgDM80pSD5MpQUF/5TQ+ga+HgcEE1J3/Te8Zb691wzDy8
uBM/H1z6lQ9HzqjiIve7Bi2xZRZ5bOZccq9GydgvyMex4IozkId4XfPfFNKSmn4w
LZZed2paceVhFWPWwsXjEAhkB6P1NPVSpnZpBk3zCOVYqnlgDGHPNMWNypVnH72A
cKsj5whWcdQ5j7HPpLyPdnGYRubZXSbVwE0fKP0weuuyN0Ks/WyyZ2o9X+bkttz3
jTgl6FUxMUxWnn48F+ASTD6CI9+0s6yFbY+Jhnv4RMOFPb0LPCyFXZVGSkmSR0yf
PhCmuMrJAoGBAPPzG/AQxtD2NNliEYEwcRnpPVAQa7KSlqrJIb2UCouExhnDWZ6o
BdLjAR8NrHH1ur1ElfwW59YtUsgIp32aVG76IeLvQHw4brLihIOcjtFCEuWBBXLQ
uX0fDdI/71GXU4cqjBqRdDzsTjtXWFNlhmAPDvNoCPTcumnFIFFjQcBlAoGBAO2z
WLy5jKqa4N3NrUKIEY7EhJ/75kfzOVQQjpo18lbL3BVidzjeK348LxBnmx25y5xb
DymoUu4OdmyAuQtnv66GkOZhDpnhEQu8wkuQnBqVgXtEbNDofQwYI/U4aJyAvtLW
q2Ok0uY4+99um7Q0GG17zNc4tnAS7cirZC7Dnp6XAoGBAKS5SusemPFu3p7O7pz6
ddSWPvV6MQ7ClwQ5jhPyC/DLteydkT1lnZEaAZ7TX9cPo4m77z7qxJ9FuXkjBt30
QQEy24DeJv/6Jx2ZgPtR0soQQKxCI8i0khufxXhr/ZBti1Rg8XvbLc8ZjXXac+TU
UBk68dCANlQJW8Kh/kGWsUZVAoGABcgI7n4s17FwqrRn9GhO1QQena2IylM2H79P
WJzbShUnQzXj5HQy5p0cH/AFK9HrC+CDG+ZGLhgX9UekOIzLcrk/KPtPWZrJyVlL
+H6J7XOZdKATbXlaIUMtDLfUg4n2GjaycHf/0S2top+UFev2dCNAtjNg7JTpR6oz
g5eqcf0CgYA0oDe6WKDjjko/BZ5AaY5J84J1If08xt/4pO+BSJK2NE4qxSTQJLU+
Fgx9By97ZmnxKSHlTY73d18F364rdyIpBvL3mJ2nJ8s49tsZAlk/kglbD88gqXN0
Fd8h8qovkKZ1+EwY7B0JVBOFw/87C36Guk/xztxA3m2IpSRtVAB4Tw==
-----END RSA PRIVATE KEY-----%  
          script: |
            cd app
            git pull origin main
            npm install
            pm2 restart app.js
