name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "21"

      - name: Install dependencies
        run: npm install

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Debug Secrets (Optional, for troubleshooting only)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "Host: ${{ secrets.EC2_HOST }}"
          echo "User: ${{ secrets.EC2_USER }}"
          echo "Key: (hidden)"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /path/to/your/app

            git pull origin main

            echo "Setting environment variables"
            export DB_USER="${{ secrets.DB_USER }}"
            export DB_HOST="${{ secrets.DB_HOST }}"
            export DB_NAME="${{ secrets.DB_NAME }}"
            export DB_PASSWORD="${{ secrets.DB_PASSWORD }}"
            export DB_PORT="${{ secrets.DB_PORT }}"

            npm install

            pm2 restart app || pm2 start app.js --name app
